### ISSUE TITLE
page-location-example broken

### ISSUE THREAD

**Issue by imshuffling** [contentful/apps#411] opened 2021-08-16 16:45 UTC
**Describe the bug**
Using the latest package.json on the example "Page-location" App

**To Reproduce**
- `npm install` page-location app
- `npm start`

**Expected behavior**
App development server starts

**Screenshots**
![image](https://user-images.githubusercontent.com/739061/129599436-5311c063-93f4-4b37-8961-9be8552f2c81.png)

**Desktop (please complete the following information):**
Mac OS - Catalina

**Additional context**

**Comment by kdamball** [comment] 2021-08-17 09:56
Hi @imshuffling, thanks for the report! As a quick followup, what node version are you using?

**Comment by imshuffling** [comment] 2021-08-17 10:16
Hey @kdamball  Node version `v14.0.0`, Do you think thats the issue?

**Comment by kdamball** [comment] 2021-08-17 10:25
@imshuffling  We're planning on migrating this to a more reliable setup, however I am still able to build this. However, as the `.nvmrc` in the project is on `v10.22.1`, I'd suggest trying that version and see if you can still build the example project

**Comment by kdamball** [comment] 2021-08-19 11:28
Closing this for now. Feel free to reopen in case the issue is ongoing

**Closed by kdamball** 2021-08-19 11:28 UTC
